<?php
    DEFINE('WEBPATH','http://localhost:1020/shoutitout/');
    DEFINE('HOST','localhost');
    DEFINE('PASSWORD','');
    DEFINE('USER','root');
    DEFINE('PAGES','pages/');
    DEFINE('CSS','css/');
    DEFINE('INC','includes/');
?>